name: _a_cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  _j_build:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, '_ci_')"
    
    steps:
    - uses: actions/checkout@v2
      
    - name: _s_build
      run: |
        cd "org.arbweb.xam.ui"
        nuget restore
        msbuild org.arbweb.xam.ui.sln /p:Configuration=Release

    - name: _s_publish
      if: "contains(github.event.head_commit.message, '_cd_')"
      env:
        nuget_key: ${{ secrets.arbweb_nuget_key }}
      run: |
        ls
        exit 1
        nuget pack org.arbweb.xam.ui.nuspec        
        nuget setapikey "$nuget_key"
        nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
