name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build the solution
      run: |
        cd "org.arbweb.xam.ui"
        dir
        dotnet build org.arbweb.xam.ui.sln
        nuget pack org.arbweb.xam.ui.0.5.2.nuspec
